# Generated by Django 5.0.6 on 2024-07-03 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Nombre')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('upadated', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('upadated', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categories', models.ManyToManyField(to='blog.categories', verbose_name='Categorías')),
            ],
        ),
    ]
