# Generated by Django 5.0.6 on 2024-07-09 12:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='1', verbose_name='Text'),
        ),
    ]
